### ISSUE TITLE
feature plans

### ISSUE THREAD

**Issue by vtolstov** [silas/dag#6]
very big thanks for package, without terraform stuff, with pure DAG methods. Do you plan to support it in feature and remove other don't needed stuff like Diagnostic interface and methods?

**Comment by silas** [comment]
Sorry, I missed this issue.

I plan to keep it in sync for the foreseeable future and I might create a v2 at some point with diagnostics and other terraform interfaces removed, but for now I want to keep the interface fairly compatible with terraform as they've recently made the terraform import path internal and this gives people a migration path.
